{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "food-app.fullname" . }}-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ include "food-app.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "food-app.fullname" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort | default 3000 }}
          env:
            - name: REACT_APP_API_BASE_URL
              value: {{ .Values.frontend.env.REACT_APP_API_BASE_URL | default "" | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "food-app.fullname" . }}-frontend
spec:
  type: ClusterIP
  selector:
    app: {{ include "food-app.fullname" . }}-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.containerPort | default 3000 }}
{{- end }}
