{{- if .Values.images.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "food-app.fullname" . }}-images
spec:
  replicas: {{ .Values.images.replicas }}
  selector:
    matchLabels:
      app: {{ include "food-app.fullname" . }}-images
  template:
    metadata:
      labels:
        app: {{ include "food-app.fullname" . }}-images
    spec:
      containers:
        - name: images
          image: "{{ .Values.images.image.repository }}:{{ .Values.images.image.tag }}"
          ports:
            - containerPort: {{ .Values.images.port }}
          env:
            - name: MONGO_URI
              value: {{ quote .Values.commonEnv.MONGO_URI }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "food-app.fullname" . }}-images
spec:
  selector:
    app: {{ include "food-app.fullname" . }}-images
  ports:
    - port: {{ .Values.images.port }}
      targetPort: {{ .Values.images.port }}
  type: ClusterIP
{{- end }}
