{{- if .Values.mongo.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "food-app.fullname" . }}-mongo-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.mongo.pvc.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "food-app.fullname" . }}-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "food-app.fullname" . }}-mongo
  template:
    metadata:
      labels:
        app: {{ include "food-app.fullname" . }}-mongo
    spec:
      containers:
        - name: mongo
          image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
          args: ["--bind_ip_all"]
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: {{ include "food-app.fullname" . }}-mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "food-app.fullname" . }}-mongo
spec:
  selector:
    app: {{ include "food-app.fullname" . }}-mongo
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP
{{- end }}
