imagePullSecrets: []
imagePullPolicy: IfNotPresent

mongo:
  enabled: true
  image:
    repository: mongo
    tag: "6.0"
  service:
    port: 27017
  pvc:
    enabled: true
    storage: 5Gi

frontend:
  enabled: true
  image:
    repository: techcoms/food-frontend
    tag: "1.0.0"
  replicas: 2
  service:
    port: 80
  containerPort: 3000

orders:
  enabled: true
  image:
    repository: techcoms/orders
    tag: "1.0.0"
  replicas: 1
  port: 4002

payments:
  enabled: true
  image:
    repository: techcoms/payments
    tag: "1.0.0"
  replicas: 1
  port: 4003

options:
  enabled: true
  image:
    repository: techcoms/options
    tag: "1.0.0"
  replicas: 1
  port: 4004

images:
  enabled: true
  image:
    repository: techcoms/images
    tag: "1.0.0"
  replicas: 1
  port: 4005

ingress:
  enabled: true
  className: nginx
  host: food.example.com

# ðŸ”¥ THIS WAS MISSING
commonEnv:
  MONGO_URI: "mongodb://food-app-mongo:27017/fooddb"
