imagePullSecrets: []
imagePullPolicy: IfNotPresent

mongo:
  enabled: true
  image:
    repository: mongo
    tag: "6.0"
  service:
    port: 27017
  pvc:
    enabled: true
    storage: 5Gi

frontend:
  enabled: true
  image:
    repository: techcoms/food-frontend
    tag: "latest"
  replicas: 2
  service:
    port: 80
  containerPort: 3000

  # âœ… FIXED LOCATION
  env:
    REACT_APP_API_BASE_URL: ""

orders:
  enabled: true
  image:
    repository: techcoms/orders
    tag: "latest"
  replicas: 1
  port: 4002

payments:
  enabled: true
  image:
    repository: techcoms/payments
    tag: "latest"
  replicas: 1
  port: 4003

options:
  enabled: true
  image:
    repository: techcoms/options
    tag: "latest"
  replicas: 1
  port: 4004

images:
  enabled: true
  image:
    repository: techcoms/images
    tag: "latest"
  replicas: 1
  port: 4005

ingress:
  enabled: true
  className: nginx
  host: food.example.com

commonEnv:
  MONGO_URI: "mongodb://food-app-mongo:27017/fooddb"

