imagePullSecrets: []
imagePullPolicy: IfNotPresent

# -------------------------
# MongoDB
# -------------------------
mongo:
  enabled: true
  image:
    repository: mongo
    tag: "6.0"
  service:
    port: 27017
  pvc:
    enabled: true
    storage: 5Gi

# -------------------------
# Frontend
# -------------------------
frontend:
  enabled: true
  image:
    repository: techcoms/food-frontend
    tag: "1.0.0"
  replicas: 2
  service:
    type: ClusterIP
    port: 80
  containerPort: 3000

# -------------------------
# Orders
# -------------------------
orders:
  enabled: true
  image:
    repository: techcoms/orders
    tag: "1.0.0"
  replicas: 1
  port: 4002

# -------------------------
# Payments
# -------------------------
payments:
  enabled: true
  image:
    repository: techcoms/payments
    tag: "1.0.0"
  replicas: 1
  port: 4003

# -------------------------
# Options
# -------------------------
options:
  enabled: true
  image:
    repository: techcoms/options
    tag: "1.0.0"
  replicas: 1
  port: 4004

# -------------------------
# Images
# -------------------------
images:
  enabled: true
  image:
    repository: techcoms/images
    tag: "1.0.0"
  replicas: 1
  port: 4005

# -------------------------
# Common Environment Variables
# -------------------------
commonEnv:
  MONGO_URI: "mongodb://mongo:27017/fooddb"

# -------------------------
# Ingress
# -------------------------
ingress:
  enabled: true
  className: nginx
  host: food.example.com
