name: Build & Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: techcoms

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # ---------- Orders ----------
      - name: Build & Push Orders
        uses: docker/build-push-action@v5
        with:
          context: ./orders
          push: true
          tags: |
            techcoms/orders:latest

      # ---------- Payments ----------
      - name: Build & Push Payments
        uses: docker/build-push-action@v5
        with:
          context: ./payments
          push: true
          tags: |
            techcoms/payments:latest

      # ---------- Options ----------
      - name: Build & Push Options
        uses: docker/build-push-action@v5
        with:
          context: ./options
          push: true
          tags: |
            techcoms/options:latest

      # ---------- Images ----------
      - name: Build & Push Images
        uses: docker/build-push-action@v5
        with:
          context: ./images
          push: true
          tags: |
            techcoms/images:latest
